config/routes.rb
Rails.application.routes.draw do
  resources :ankete

   root 'ankete#index'

end

app/models/anketa.rb
class Anketa < ActiveRecord::Base

  validate do
    check_pitanja_number
  end
  belongs_to :kategorija 
  validates :naslov, presence: true
  validates :opis, presence: true
  validates :kategorija_id, presence: true
  has_many :pitanja, dependent: :destroy  
  accepts_nested_attributes_for :pitanja, :reject_if => lambda { |a| a[:sadrzaj].blank? }, :allow_destroy => true
  
  private
  
    def check_pitanja_number
      unless pitanja.size >= 1
        errors.add(:base, "Morate uneti bar jedno pitanje za svaku anketu")
      end
    end        
end

app/models/kategorija.rb
class Kategorija < ActiveRecord::Base
  has_many :ankete  
  validates :ime, presence: true, uniqueness: true
end

app/models/odgovor.rb
class Odgovor < ActiveRecord::Base
  belongs_to :pitanje
  validates :sadrzaj, presence: true  
end

app/models/pitanje.rb
class Pitanje < ActiveRecord::Base
  validate do
    check_odgovori_number
  end
  belongs_to :anketa
  has_many :odgovori, :dependent => :destroy 
  accepts_nested_attributes_for :odgovori, :reject_if => lambda { |a| a[:sadrzaj].blank? }, :allow_destroy => true   

  private

    def check_odgovori_number
      unless odgovori.size >= 2
        errors.add :odgovori, ' - Morate imati minimum dva ponudjena odgovora na svako pitanje'
      end
    end  
end

app/controllers/ankete_controller.rb
class AnketeController < ApplicationController

  expose(:ankete)
  expose(:anketa, attributes: :anketa_params)
  expose(:kategorija)
  expose(:kategorije)
  expose(:pitanja)  
    
  def index
  end

  def show
  end

  def new
    3.times do 
      pitanja = anketa.pitanja.build
      4.times { pitanja.odgovori.build }
    end
  end

  def edit
  end

  def create
    self.anketa = Anketa.new(anketa_params)
      if anketa.save
        redirect_to anketa, notice: 'Anketa je uspešno kreirana.'
      else
        render action: 'new'
      end
  end

  def update
    respond_to do |format|
      if self.anketa.update(anketa_params)
        format.html { redirect_to anketa, notice: 'Anketa je uspešno promenjena.' }
        format.json { render :show, status: :ok, location: anketa }
      else
        format.html { render :edit }
        format.json { render json: anketa.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    anketa.destroy
    respond_to do |format|
      format.html { redirect_to ankete_url, notice: 'Anketa je uspešno izbrisana.' }
      format.json { head :no_content }
    end
  end

  private

    def anketa_params
      params.require(:anketa).permit(:naslov, :opis, :kategorija_id, :pitanja_attributes => [:id, :sadrzaj, :anketa_id, :_destroy, :odgovori_attributes => [:id, :sadrzaj, :pitanje_id, :_destroy]])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
  protect_from_forgery with: :exception
end

app/helpers/ankete_helper.rb
module AnketeHelper
  def pluralize_greska(anketa_errors_count)
    last_digit = anketa_errors_count.to_s.chars.map(&:to_i).last
    if (11..19) === anketa_errors_count
      return anketa_errors_count + "grešaka sprečava"
    else
      if last_digit == 1
        return "#{last_digit} greška sprečava"
      elsif last_digit === (2..4)
        return anketa_errors_count + "greške sprečavaju"
      elsif last_digit === (5..9)
        return anketa_errors_count + "grešaka sprečavaju" 
      elsif last_digit == 0
        return anketa_errors_count + "grešaka sprečavaju"                 
      end       
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ankete/_form.html.haml
= nested_form_for anketa, :html => { :class => 'form-horizontal' } do |f|
  - if anketa.errors.any?
    #error_explanation
      .alert.alert-dismissable.alert-danger
        %strong= "#{pluralize_greska(anketa.errors.count)} Anketu da bude uspešno sačuvana :"
        %ul
          - anketa.errors.full_messages.each do |msg|
            %li= msg
  .well.bs-component
    .form-group
      = f.label :naslov
      = f.text_field :naslov, class: 'form-control'
    .form-group
      = f.label :opis
      = f.text_area :opis, class: 'form-control'
    .form-group
      = f.label :kategorija_id
      = f.select :kategorija_id, kategorije.collect {|p| [ p.	ime, p.id ] }, {}, :class => 'form-control', :include_blank => false, class: 'form-control'
  = f.fields_for :pitanja do |b|
    .well.bs-component
      .form-group
        .col-lg-9
          = f.label "pitanje"
          = b.text_field :sadrzaj, class: 'form-control'
        .col-lg-2
        .col-lg-1
          = b.link_to_remove "X", :class => "btn btn-danger btn-xs"
      = b.fields_for :odgovori do |p|
        = p.label :sadrzaj, "Odgovor"
        = p.text_field :sadrzaj 
        = p.link_to_remove "X", :class => "btn btn-danger btn-xs"
      = b.link_to_add "Dodaj odgovor", :odgovori, :class => "btn btn-info btn-xs"      
  %center
    = f.link_to_add "++++++ Dodaj pitanje ++++++++", :pitanja, :class => "btn btn-info btn-xl"
  %center 
    %br 
      = f.submit 'Sacuvaj Anketu', :class => "btn btn-default"

app/views/ankete/edit.html.haml
.row
  .col-lg-3
  .col-lg-6
    %h1 Izmeni Anketu
    
    = render 'form'
    %center
      = link_to 'Nazad', ankete_path, :class => "btn btn-danger"
  .col-lg-3   

app/views/ankete/index.html.haml
.page-header
%table.table.table-striped
	%thead
		%tr
			%th= 'id'
			%th= 'naslov'
			%th= 'opis'
			%th= 'created_at'
			%th= 'actions'
	%tbody
	- ankete.each do |anketa|
		%tr
			%td
				= link_to anketa.id, anketa_path(anketa)
			%td
				=anketa.naslov
			%td
				=anketa.opis
			%td
				=anketa.created_at								
			%td
				= link_to 'edit', edit_anketa_path(anketa), :class => 'btn btn-primary btn-xs' 
				= link_to 'destroy', anketa_path(anketa), :method => :delete,
				:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
				:class => 'btn btn-danger btn-xs'

= link_to 'new', new_anketa_path, :class => 'btn btn-primary btn-xs'

app/views/ankete/new.html.haml
.row
  .col-lg-3
  .col-lg-6
    %h1 Nova Anketa
    
    = render 'form'
    %center
      %br
        = link_to 'Nazad', ankete_path, :class => "btn btn-danger"
  .col-lg-3  

app/views/ankete/show.html.haml
.row
  .col-lg-1
  .col-lg-5
    .well.bs-component
      %legend  
        =anketa.naslov
      %p.text-info
        =anketa.opis   
      = form_tag root_path, :multipart => true, method: :post, :html => { :class => 'form-horizontal' } do
        - anketa.pitanja.each do |pitanje| 
          %h4
            %b  
              =pitanje.sadrzaj
          %strong
          - pitanje.odgovori.each do |odgovor|
            .form-group
              %b 
                =radio_button_tag 'odgovor', odgovor
                =odgovor.sadrzaj
        .form-group
          = submit_tag 'Rezultat', :class => "btn btn-primary"      
                 
  .col-lg-5  
    .page-header
      %h1
        =anketa.naslov
  .col-lg-1

app/views/layouts/_footer.html.haml
%footer
	%br
	.row
		.col-lg-4
		.col-lg-4
			%center	
				%ul.breadcrumb
					%li.active
						%p.lead
							2015 © - Anketar
		.col-lg-4

app/views/layouts/_navbar.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="#") ANKETAR
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li= link_to "Početna", root_path, class: 'bold-text-navbar'
        %li= link_to "Nova Anketa", new_anketa_path, class: 'bold-text-navbar'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anketar</title>
  <%= stylesheet_link_tag    'yeti', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'yeti', :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %> 
	<div class="container theme-showcase">
		<div class="row">      	
			<%= yield %>
		</div>   
	<%= render 'layouts/footer' %> 
</body>
</html>